name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          
      - name: Install maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash
        
      - name: Export path
        run: echo "$PATH":"$HOME/.maestro/bin" >> $GITHUB_PATH
        
      - name: Install idb
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
        
      - run: xcodebuild -project MaestroDemo.xcodeproj -scheme MaestroDemo -destination 'platform=iOS Simulator,name=iPhone 14'
            
      - name: Run tests
        run: |
          maestro test .maestro/test.yaml
          14
