name: iOS starter workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ios_maestro:
    name: Build app and run maestro test using iPhone 14 Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Xcode select
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          sudo xcode-select -p
      # - name: Check firewall
      #   run: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate --getblockall --getallowsigned --getstealthmode

      # - name: Open Network pane in Prefereneces
      #   run: open /System/Library/PreferencePanes/Network.prefPane/

      # - name: Check Ports 22087 and 9080
      #   run: |
      #     sudo lsof -i tcp:22087
      #     sudo lsof -i tcp:9080

      # - name: Check hosts
      #   run: cat /etc/hosts

      # - name: Check All Ports
      #   run: netstat -an

      # - name: Check Ports for LISTEN
      #   run: netstat -an | grep LISTEN

      # - name: Install maesttro via brew
      #   run: |
      #     brew tap mobile-dev-inc/tap
      #     brew install maestro

      - name: Install maestro via curl
        run: export MAESTRO_VERSION=1.18.5; curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Export path
        run: echo "$PATH":"$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Check maestro version
        run: maestro -v

      - name: Install idb
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      # - name: Install idb client
      #   run: pip3 install fb-idb

      # - name: List simulators
      #   run: xcrun simctl list devices

      # - name: Run simulator
      #   run: |
      #     xcrun simctl erase 5DD249BC-7C55-4BCD-BC94-03B668FA93C6
      #     xcrun simctl boot 5DD249BC-7C55-4BCD-BC94-03B668FA93C6

      # - name: Extract simulator uid
      #   run: |
      #     echo "SIM_ID=$(xcrun simctl list devices available | grep 'iPhone 14' | grep -E -o -i '([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})' | head -1)" >> $GITHUB_ENV

      # - name: Get simulator id
      #   run: echo "${{ env.SIM_ID }}"

      - name: Build app
        run: |
          xcodebuild -project "MaestroDemo.xcodeproj" \
                    -scheme "MaestroDemo" \
                    -destination "platform=iOS Simulator,name=iPhone 14" \
                    -derivedDataPath "/tmp/app" \
                    -configuration "Debug"

      # - name: Boot simulator & run tests
      #   run: |
      #     xcrun simctl erase "${{ env.SIM_ID }}"
      #     xcrun simctl boot "${{ env.SIM_ID }}"
      #     xcrun simctl install booted "/tmp/app/Build/Products/Debug-iphonesimulator/MaestroDemo.app"
      #     maestro test .maestro/test.yaml

      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
          os_version: '16.2'

      - name: install app in simulator
        run: xcrun simctl install booted "/tmp/app/Build/Products/Debug-iphonesimulator/MaestroDemo.app"

      # - name: Open simulator
      #   run: open /Applications/Xcode_14.0.1.app/Contents/Developer/Applications/Simulator.app

      # - name: launch app
      #   run: xcrun simctl launch booted com.aelzohry.MaestroDemo

      - name: Run app tests
        run: maestro test .maestro/test.yaml

      # - name: Run settings test
      #   run: maestro record .maestro/settings.yaml

      # - name: Run maestro hierarchy
      #   run: maestro hierarchy

      # - name: Run maestro studio
      #   if: always()
      #   run: maestro studio

      # - name: Check Ports for LISTEN
      #   if: always()
      #   run: netstat -an | grep LISTEN

      # - uses: OrbitalOwen/desktop-screenshot-action@0.1
      #   if: always()
      #   with:
      #     file-name: 'desktop.jpg'

      # - name: take screenshot
      #   if: always()
      #   run: xcrun simctl io booted screenshot screenshot.png

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: my-artifact
      #     path: screenshot.png

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-artifact
          path: ~/Library/Logs/maestro/

      # - name: Run maestro hierarchy
      #   run: maestro hierarchy

      # - name: Test idb connection
      #   run: |
      #     idb list-targets
      #     idb launch com.apple.Preferences
      #     idb ui describe-all
