name: iOS starter workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build app and run maestro test using iPhone 14 Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - uses: actions/setup-java@v2
      #   with:
      #     distribution: adopt
      #     java-version: 11

      - name: Xcode select
        run: |
          sudo xcode-select -p
          sudo xcode-select --switch /Applications/Xcode_14.1.app
          sudo xcode-select -p

      # - name: Install maesttro via brew
      #   run: |
      #     brew tap mobile-dev-inc/tap
      #     brew install maestro

      - name: Install maestro via curl
        run: export MAESTRO_VERSION=1.20.0; curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Export path
        run: echo "$PATH":"$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Check maestro version
        run: maestro -v

      - name: Install idb
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      # - name: Install idb client
      #   run: pip3 install fb-idb

      - name: List simulators
        run: xcrun simctl list devices

      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'
          os_version: '16.1'

      # - name: Build app
      #   run: |
      #     xcodebuild -project "MaestroDemo.xcodeproj" \
      #               -scheme "MaestroDemo" \
      #               -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" \
      #               -derivedDataPath "/tmp/app" \
      #               -configuration "Debug"

      # - name: Check firewall
      #   run: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate --getblockall --getallowsigned --getstealthmode

      # - name: Open simulator
      #   run: open /Applications/Xcode_14.2.app/Contents/Developer/Applications/Simulator.app

      # - name: Open Network pane in Prefereneces
      #   run: open /System/Library/PreferencePanes/Network.prefPane/

      # - name: install app in simulator
      #   run: xcrun simctl install booted "/tmp/app/Build/Products/Debug-iphonesimulator/MaestroDemo.app"

      # - name: Run app tests
      #   run: maestro record .maestro/test.yaml

      - name: Run settings test
        run: maestro record .maestro/settings.yaml

      # - uses: OrbitalOwen/desktop-screenshot-action@0.1
      #   if: always()
      #   with:
      #     file-name: 'desktop.jpg'

      # - name: launch app
      #   if: always()
      #   run: xcrun simctl launch booted com.aelzohry.MaestroDemo

      # - name: take screenshot
      #   if: always()
      #   run: xcrun simctl io booted screenshot screenshot.png

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: my-artifact
      #     path: screenshot.png
#      - name: Run maestro hierarchy
#        run: maestro hierarchy

# - name: Test idb connection
#   run: idb list-targets
#          idb launch com.apple.Preferences
#          idb ui describe-all
