name: iOS starter workflow

on: workflow_dispatch

jobs:
  ios_maestro:
    name: Build app and run maestro test using iPhone 14 Simulator
    runs-on: macos-latest

    steps:
      - name: Install idb
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      # NOTE: it must be v2, since v3 is causing issues with maestro test step
      # - name: Setup Java
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: temurin
      #     java-version: 11

      - name: Checkout
        uses: actions/checkout@v3

      - name: Xcode select
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          sudo xcode-select -p

      # Install Maestro via curl
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Check maestro version
        run: maestro --version

      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
          os_version: '16.2'
          # shutdown_after_job: false

      - name: Build app
        run: |
          xcodebuild -project "MaestroDemo.xcodeproj" \
                    -scheme "MaestroDemo" \
                    -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" \
                    -derivedDataPath "/tmp/app" \
                    -configuration "Debug" build

      - name: Install app & Run e2e tests
        run: |
          xcrun simctl install booted "/tmp/app/Build/Products/Debug-iphonesimulator/MaestroDemo.app"
          maestro test .maestro/test.yaml
      # xcrun simctl shutdown all
      # - name: Run setting tests
      #   run: |
      #     maestro test .maestro/settings.yaml
      #     xcrun simctl shutdown all

      # - name: Install app
      #   run: xcrun simctl install booted "/tmp/app/Build/Products/Debug-iphonesimulator/MaestroDemo.app"

      # - name: Run tests
      #   run: maestro test .maestro/test.yaml

      # - name: Open simulator
      #   run: open /Applications/Xcode_14.0.1.app/Contents/Developer/Applications/Simulator.app

      # - name: launch app
      #   run: xcrun simctl launch booted com.aelzohry.MaestroDemo

      # - name: Check Ports for LISTEN
      #   if: always()
      #   run: netstat -an | grep LISTEN

      # - uses: OrbitalOwen/desktop-screenshot-action@0.1
      #   if: always()
      #   with:
      #     file-name: 'desktop.jpg'

      # - name: take screenshot
      #   if: always()
      #   run: xcrun simctl io booted screenshot screenshot.png

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: my-artifact
      #     path: screenshot.png

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs-artifact
          path: ~/Library/Logs/maestro/

      # - name: Install maestro via curl
      #   run: export MAESTRO_VERSION=1.18.5; curl -Ls "https://get.maestro.mobile.dev" | bash

      # - name: Export path
      #   run: echo "$PATH":"$HOME/.maestro/bin" >> $GITHUB_PATH

      # - name: Install idb client
      #   run: pip3 install fb-idb

      # - name: List simulators
      #   run: xcrun simctl list devices

      # - name: Run simulator
      #   run: |
      #     xcrun simctl erase 5DD249BC-7C55-4BCD-BC94-03B668FA93C6
      #     xcrun simctl boot 5DD249BC-7C55-4BCD-BC94-03B668FA93C6

      # - name: Extract simulator uid
      #   run: |
      #     echo "SIM_ID=$(xcrun simctl list devices available | grep 'iPhone 14' | grep -E -o -i '([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})' | head -1)" >> $GITHUB_ENV

      # - name: Boot simulator & run tests
      #   run: |
      #     xcrun simctl erase "${{ env.SIM_ID }}"
      #     xcrun simctl boot "${{ env.SIM_ID }}"
      #     xcrun simctl install booted "/tmp/app/Build/Products/Debug-iphonesimulator/MaestroDemo.app"
      #     maestro test .maestro/test.yaml

      # - name: Test idb connection
      #   run: |
      #     idb list-targets
      #     idb launch com.apple.Preferences
      #     idb ui describe-all

      # - name: Check firewall
      #   run: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate --getblockall --getallowsigned --getstealthmode

      # - name: Open Network pane in Prefereneces
      #   run: open /System/Library/PreferencePanes/Network.prefPane/

      # - name: Check Ports 22087 and 9080
      #   run: |
      #     sudo lsof -i tcp:22087
      #     sudo lsof -i tcp:9080

      # - name: Check hosts
      #   run: cat /etc/hosts

      # - name: Check All Ports
      #   run: netstat -an

      # - name: Check Ports for LISTEN
      #   run: netstat -an | grep LISTEN
