name: iOS maestro test action

on: workflow_dispatch

jobs:
  ios_maestro:
    name: Build app and run maestro test using iPhone 14 Simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
          os_version: '16.2'

      - uses: dniHze/maestro-test-action@v1
        with:
          flow: .maestro/settings.yaml
          report: report.xml
          version: 1.26.1

      - name: Upload maestro logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-artifact
          path: ~/Library/Logs/maestro/

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: report.xml
